services:
  # Redpanda - Kafka-compatible streaming platform
  redpanda:
    image: redpandadata/redpanda:latest
    container_name: marketpulse-redpanda
    command:
      - redpanda
      - start
      - --kafka-addr internal://0.0.0.0:9092,external://0.0.0.0:${REDPANDA_PORT}
      - --advertise-kafka-addr internal://redpanda:9092,external://localhost:${REDPANDA_PORT}
      - --pandaproxy-addr internal://0.0.0.0:8082,external://0.0.0.0:18082
      - --advertise-pandaproxy-addr internal://redpanda:8082,external://localhost:18082
      - --schema-registry-addr internal://0.0.0.0:8081,external://0.0.0.0:18081
      - --rpc-addr redpanda:33145
      - --advertise-rpc-addr redpanda:33145
      - --mode dev-container
      - --smp 1
      - --default-log-level=info
    ports:
      - "${REDPANDA_PORT}:9092"
      - "${REDPANDA_ADMIN_PORT}:9644"
      - "18081:8081"
      - "18082:8082"
    networks:
      - marketpulse-network
    volumes:
      - redpanda-data:/var/lib/redpanda/data
    healthcheck:
      test: ["CMD-SHELL", "rpk cluster health | grep -E 'Healthy:.+true' || exit 1"]
      interval: 15s
      timeout: 3s
      retries: 5
      start_period: 5s

  # Market Pulse API Service (to be implemented in Phase 1)
  # pulse-service:
  #   build: .
  #   container_name: marketpulse-api
  #   env_file: .env
  #   environment:
  #     - NODE_ENV=${NODE_ENV}
  #     - PORT=${PORT}
  #     - REDPANDA_BROKERS=redpanda:9092
  #     - DATA_START_DATE=${DATA_START_DATE}
  #     - DATA_END_DATE=${DATA_END_DATE}
  #   ports:
  #     - "${PORT}:${PORT}"
  #   depends_on:
  #     redpanda:
  #       condition: service_healthy
  #   networks:
  #     - marketpulse-network
  #   volumes:
  #     - ./data:/app/data:ro

networks:
  marketpulse-network:
    driver: bridge

volumes:
  redpanda-data:
